name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cmake build 
      run: mkdir build && cd build && cmake ..

    - name: make main
      run: cd build && make
    
    - name: run tests
      run: make test
